name: root
channels:
  - defaults
  - pyviz/label/dev
  - bokeh/label/dev
  - intake
  - conda-forge
dependencies:
  - jupyterhub==0.9.2
  - bokeh=0.13
  - bqplot
  - cython
  - cytoolz
  - dask=0.19
  - dask-ml
  - datashader
  - distributed=1.23
  - fastparquet
  - gcsfs=0.1.2
  - ipywidgets
  - ipyleaflet
  - jupyter
  - jupyterlab=0.34.2
  - jupyterlab_launcher=0.13.1
  - jupyter_client
  - holoviews
  - libsodium
  - lz4
  - matplotlib
  - nb_conda_kernels
  - nomkl
  - numba
  - numcodecs
  - numpy=1.15
  - pandas=0.23
  - python-blosc
  - pyzmq
  - s3fs
  - scipy
  - scikit-image
  - scikit-learn
  - xarray=0.10.9
  - zarr=2.2.0
  - intake-xarray
  - graphviz
  - python-graphviz
  - gsw
  - pip:
    - click
    - jedi
    - kubernetes==6.0.0
    - dask-kubernetes==0.5.0
    - nbserverproxy==0.8.1
